# Feature Engineering

### Imports

In [2]:
import pandas as pd
import sys
from pathlib import Path
sys.path.append(str(Path("..").resolve()))
from src.config import RAIN_COLS_HEB_TO_ENG
from src.feature_engineering import modify_rainfall_df_values, group_rainfall_by_day_and_hour, merge_rain_to_trips_df

In [6]:
### Import Trips interim dataframe
df_trips = pd.read_csv(r'../data/interim_data/telaviv_buses_jan2024_sample_cleaned.csv')

### Rainfall
Rainfall data was obtained from the Israeli Meteorological Service (IMS) open data portal:
https://ims.gov.il/he/data_gov

In [7]:
### Importing rainfall data collected by the Israeli Meteorological Service (IMS)
df_rain = pd.read_csv(r'../data/external/rainfall_tlv_jan_2024.csv')

### Renaming its columns to english for easy processing
df_rain = df_rain.rename(columns=RAIN_COLS_HEB_TO_ENG)

### Modifying value types
df_rain = modify_rainfall_df_values(df_rain)

### Grouping (sum) rainfall by day and hour 
rain_grouped_df = group_rainfall_by_day_and_hour(df_rain)

### Merge the rainfall (mm) to th trips df - so each trip will have the amount of rainfall at the time (hour) of the trip
df_trips = merge_rain_to_trips_df(rain_grouped_df,df_trips)

### Spatial attributes

In [22]:
df_routes = pd.read_csv(r'C:\Users\shaha\Documents\gtfs\israel-public-transportation\routes.txt')

In [41]:
df_trips[(df_trips['agency_name'] == 'Dan') & (df_trips['line_num'] == '5')].iloc[0].line_name

'משרד הרישוי/הלוחמים-חולון<->ת. רכבת תל אביב - סבידור/חנה וסע-תל אביב יפו-20'

In [29]:
df_routes.iloc[0]

route_id                                                            1
agency_id                                                          25
route_short_name                                                    1
route_long_name     ת. רכבת יבנה מערב-יבנה<->ת. רכבת יבנה מזרח-יבנ...
route_desc                                                  67001-1-#
route_type                                                          3
route_color                                                       NaN
Name: 0, dtype: object

In [33]:
df_routes[(df_routes['agency_id'] ==5) & (df_routes['route_short_name'] == '5')]

,route_id,agency_id,route_short_name,route_long_name,route_desc,route_type,route_color
492,2259,5,5,ת. רכבת תל אביב סבידור/על פרשת דרכים-תל אביב י...,25005-1-0,3,NaN
493,2261,5,5,משרד הרישוי/הלוחמים-חולון<->ת. רכבת תל אביב - ...,25005-2-0,3,NaN
494,2262,5,5,אזור התעשייה-בני ברק<->בית העלמין/חזון אי''ש-ב...,26005-1-0,3,NaN
495,2263,5,5,בית העלמין/חזון אי''ש-בני ברק<->אזור התעשייה-ב...,26005-2-0,3,NaN

In [28]:
df_trips[]

,date,day,hour_rounded,line_num,line_name,direction,alternative,agency_name,route_type,origin_city,...,route_length_km,departure_time_planned,arrival_time_planned,duration_min_planned,duration_min_actual,duration_difference_min,speed_kmh_planned,speed_kmh_actual,SIRI_id,rainfall_mm
0,2024-01-08,Monday,10,10,חניון אגד/חורשת היובל-חולון<->מסוף אזורי חן-תל...,2.0,0,Dan,bus,חולון,...,20.266,10:55:00,11:57:59,63,NaN,NaN,19.3,NaN,58732431,0.0
1,2024-01-08,Monday,3,2,פרופ' ישעיהו ליבוביץ'/הרב יעקב טראב-תל אביב יפ...,2.0,0,Dan,bus,תל אביב יפו,...,17.727,03:25:00,04:23:59,59,63.0,4.0,18.0,16.9,58796383,0.0
2,2024-01-10,Wednesday,4,910,ת. מרכזית חוף הכרמל/רציפים בינעירוני-חיפה<->ת....,2.0,#,Egged,bus,חיפה,...,84.623,04:40:00,06:10:08,90,130.0,40.0,56.4,39.1,59031152,0.0
3,2024-01-08,Monday,9,7,בי''ח וולפסון-חולון<->ת. רכבת אוניברסיטה/הורדה...,2.0,0,Dan,bus,חולון,...,16.333,09:35:00,10:27:00,52,77.0,25.0,18.8,12.7,58837508,0.0
4,2024-01-09,Tuesday,6,26,קריית חינוך-תל אביב יפו<->חניון אגד/דן שומרון-...,2.0,#,Metropolin,bus,תל אביב יפו,...,20.464,06:00:00,07:05:09,65,80.0,15.0,18.9,15.3,58927747,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2024-01-11,Thursday,4,33,מסוף רדינג/רציפים-תל אביב יפו<->איצטדיון וינטר...,1.0,0,Dan,bus,תל אביב יפו,...,15.068,04:10:00,05:09:20,59,59.0,0.0,15.3,15.3,59141894,0.2
996,2024-01-10,Wednesday,4,62,מסוף רדינג/רציפים-תל אביב יפו<->בי''ח שיב''א/ש...,1.0,0,Dan,bus,תל אביב יפו,...,13.604,04:25:00,05:13:56,49,58.0,9.0,16.7,14.1,59029211,0.0
997,2024-01-06,Saturday,16,126,מסוף אזורי חן-תל אביב יפו<->חניון אגד/דן שומרו...,2.0,#,Metropolin,bus,תל אביב יפו,...,18.392,16:45:00,17:47:08,62,87.0,25.0,17.8,12.7,58661884,0.0
998,2024-01-10,Wednesday,6,57,ת. רכבת אוניברסיטה/איסוף-תל אביב יפו<->איצטדיו...,1.0,0,Dan,bus,תל אביב יפו,...,12.141,06:10:00,06:54:59,45,19.0,-26.0,16.2,38.3,59043283,0.0
999,2024-01-08,Monday,4,271,מסוף אונברסיטת ת''א-תל אביב יפו<->שדרות ירושלי...,1.0,#,Egged,bus,תל אביב יפו,...,16.841,04:15:00,05:01:59,47,46.0,-1.0,21.5,22.0,58800960,0.0

In [42]:
pd.read_csv(r'C:\Users\shaha\Documents\gtfs\israel-public-transportation\stops.txt')

,stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,location_type,parent_station,zone_id
0,1,38831,בי''ס בר לב/בן יהודה,רחוב: בן יהודה 74 עיר: כפר סבא רציף: קומה:,32.183985,34.917554,0,NaN,38831.0
1,2,38832,הרצל/צומת בילו,רחוב: הרצל עיר: קרית עקרון רציף: קומה:,31.869152,34.819641,0,NaN,38832.0
2,3,38833,מרכז ראשונים/הנחשול,רחוב: הנחשול 30 עיר: ראשון לציון רציף: קומה:,31.984553,34.782828,0,NaN,38833.0
3,4,38834,משה פריד/יצחק משקה,רחוב: משה פריד 5 עיר: רחובות רציף: קומה:,31.888325,34.790700,0,NaN,38834.0
4,6,38836,ת. מרכזית לוד/הורדה,רחוב: עיר: לוד רציף: קומה:,31.956392,34.898098,0,NaN,38836.0
...,...,...,...,...,...,...,...,...,...
34977,52012,3165,פרופ' יעקב נאמן/הרב אברהם זקן,רחוב: פרופ' יעקב ישראל נאמן עיר: ירושלים רציף:...,31.742587,35.223657,0,NaN,3165.0
34978,52013,3169,שמעון מישורי/פרופ' יעקב נאמן,רחוב: שמעון מישורי 12 עיר: ירושלים רציף: קומה:,31.743668,35.225676,0,NaN,3169.0
34979,52014,3172,שמעון מישורי/גרשון אבנר,רחוב: שמעון מישורי עיר: ירושלים רציף: קומה:,31.743720,35.226651,0,NaN,3172.0
34980,52015,3174,אהליאב/ היצירה,רחוב: אהליאב 5 עיר: רמת גן רציף: קומה:,32.087443,34.802415,0,NaN,3174.0
34981,52016,3175,הרקון/ היצירה,רחוב: הרקון 16 עיר: רמת גן רציף: קומה:,32.085409,34.801967,0,NaN,3175.0